### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by woodensquares** [DamienCassou/json-navigator#11]
The README states that one would use `json-navigator-navigator` but from the code shouldn't this be `json-navigator-navigate-after-point`? 

If you don't mind an additional suggestion, the README could also mention the available navigation keys (tab/s-tab/enter) and/or mention that the resulting tree is simply a tree-widget (meaning one could use tree-mode, for example, to get additional functionality like expanding x levels etc.)

**Comment by DamienCassou** [comment]
woodensquares <notifications@github.com> writes:
> The README states that one would use `json-navigator-navigator` but
> from the code shouldn't this be `json-navigator-navigate-after-point`?

I agree with you

> If you don't mind an additional suggestion, the README could also
> mention the available navigation keys (tab/s-tab/enter) and/or mention
> that the resulting tree is simply a tree-widget (meaning one could use
> tree-mode, for example, to get additional functionality like expanding
> x levels etc.)

could you please prepare a PR with both changes?

Thanks

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by woodensquares** [comment]
done, Travis failed but it doesn't look related to my commit

**Comment by woodensquares** [comment]
done, note I also changed the header in the .el file to satisfy the linter.
