### ISSUE TITLE
json-navigator-navigate-region does not work for buffer if called interactively

### ISSUE THREAD

**Issue by Yevgnen** [DamienCassou/json-navigator#15]
Evaluating `(json-navigator-navigate-region`) works just fine for a json buffer. However, with no region activated and `M-x json-navigator-navigate-region RET`, the command exited with 

```
command-execute: The mark is not set now, so there is no region
```

But the implementation seems try to support to be called on buffer

```

;;;###autoload
(defun json-navigator-navigate-region (&optional start end)
  "Navigate JSON inside region between START and END.
If START (respectively END) is nil, use `point-min' (respectively `point-max') instead."
  (interactive "r")
  (let ((start (or start (point-min)))
        (end (or end (point-max))))
    (json-navigator-display-tree (json-navigator--read-region start end))))
```

**Comment by DamienCassou** [comment]
Can you please try #17 and tell me if it solves your problem?

> `(interactive "r")`

this line says that, interactively, the function uses the region and doesn't work if there is no region. I changed it so that the function will work interactively the same way as if called from Lisp.

**Comment by Yevgnen** [comment]
Works perfectly. Thank you very much.

**Comment by DamienCassou** [comment]
Thank you for taking the time to report the problem.
