### ISSUE TITLE
JSON readtable error: 93

### ISSUE THREAD

**Issue by philippludwig** [DamienCassou/json-navigator#25]
So I tried this mode on a pretty big json document (2600 lines), and I just get

```
JSON readtable error: 93
```

Is there anything I can do at this point?

**Comment by DamienCassou** [comment]
This error is sent by json.el, not by json-navigator. It feels like it happens when the JSON is invalid.

I'm closing the issue. Feel free to reopen if you believe there is something json-navigator can do.

**Comment by philippludwig** [comment]
But the JSON is question was valid. So I guess `json.el` can’t handle large files.
