### ISSUE TITLE
Package currently not installable because of dependency on hierarchy 0.6.0

### ISSUE THREAD

**Issue by ViktorHaag** [DamienCassou/json-navigator#27]
Hello,

Recently it seems like the `json-navigator` package is not installable because it declares dependency on `hierarchy 0.6.0`.

However, current tip of the hierarchy package in Github says it's version 0.7.0, and there seems to be no prebuilt package for hierarchy in MELPA.

This leads me to suspect that recently a prebuilt package was removed from MELPA, and the fallback to getting hierarchy's code directly from Github may not be working because of the version mismatch.

However, this is only a suspicion. I'm not sure how to correct this. I am currently using a version of Emacs that has hierarchy as built in, and I tried "requiring" hierarchy before attempting to install the json-navigator package, but that was not successful.

My "package-list-packages" currently lists json-navigator as not installed and "incompatible" because the dependency on hierarchy is not reachable.

**Comment by xuhdev** [comment]
See https://github.com/melpa/melpa/pull/9222 . This is now builtin in Emacs, so json-navigator may need some detection to understand the current Emacs installation already has it.

**Comment by DamienCassou** [comment]
Thank you for the report. This is fixed.

**Comment by ViktorHaag** [comment]
Thank you!
